import '../src/get-active-features.test.js';
import '../src/get-is-enabled.test.js';
import '../src/is-active.test.js';
import '../src/merge-features.test.js';
import '../src/get-query-features.test.js';
import '../src/remove-features.test.js';
import '../src/get-req-query-features.test.js';
import '../src/get-browser-query-features.test.js';
import '../src/get-current-active-features.test.js';
